name = "ComputabilityTheory"
uuid = "1aac4ff9-3d20-4305-ad99-6d6ea6b313c2"
authors = ["Jake W. Ireland <jakewilliami@icloud.com> and contributors"]
version = "0.1.1"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
